version: 2

general:
# Uncomment the following to specify only a specific branch
#   branches:
#     only:
#       - dev # specific branch
#       - /dev-.*/ # or regexes

jobs:
  build:
    machine: true
    working_directory: ~/ci_app
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    steps:
      - checkout
      - run:
          name: Download CLI
          command: |
            mkdir sfdx
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            ./sfdx/install
            sfdx
            mkdir tmp

      - run:
          name: Create hub key
          command: |
            echo 'make hub key'
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV

      - run:
          name: Auth Hub and Scratch Orgs
          command: |
            echo 'Running tests'
            sfdx force:auth:jwt:grant --clientid $CLIENT_ID_PRIMARY --jwtkeyfile assets/server.key --username $DEVHUB_USERNAME --instanceurl https://login.salesforce.com --setdefaultdevhubusername -a HubOrg
            sfdx force:auth:jwt:grant --clientid $CLIENT_ID_SECONDARY --jwtkeyfile assets/server.key --username anil.shivaraj@gmail.com.personal --instanceurl https://login.salesforce.com -a secondaryHubOrg

            sfdx force:auth:jwt:grant --clientid $CLIENT_ID_PRIMARY --jwtkeyfile assets/server.key --username $ORG_USERNAME --instanceurl https://test.salesforce.com -a $REQUEST_ID
            export SCRATCH_DIFF="$(eval sfdx force:source:pull -u $REQUEST_ID)"
            echo "$SCRATCH_DIFF" > SCRATCH_DIFF.TXT
            echo $SCRATCH_DIFF

            sfdx force:data:record:update -s Request_Scratch_Org__c -i $REQUEST_SFID -v "Components_Changed__c='$SCRATCH_DIFF' Diff_Check__c='false'" -u HubOrg
            sfdx force:data:record:update -s Scratch_Org_Creds__c -w "Name='ScratchOrgDetails'" -v "Components_Changed__c='$SCRATCH_DIFF' Components_Change_Updated__c=true" -u $REQUEST_ID
